### PR TITLE
Release w_dio 5.3.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [w_dio](https://github.com/Workiva/w_dio/pull/7)
	* [downgrade version](https://github.com/Workiva/w_dio/pull/8)

Requested by: @robbecker-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_dio/compare/3.1.1...Workiva:release_w_dio_5.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_dio/compare/3.1.1...5.3.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4633275085357056/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4633275085357056/?repo_name=Workiva%2Fw_dio&pull_number=9)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by taylorweil-wk — APPROVED** [review]

**Comment by taylorweil-wk** [comment]
QA+1

**Comment by taylorweil-wk** [comment]
@Workiva/release-management-p

**Comment by taylorweil-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
