### PR TITLE
RM-175157 Release w_dio 3.1.1

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Patch changes:
	* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/w_dio/pull/4)

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/w_dio/compare/3.1.0...Workiva:release_w_dio_3.1.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/w_dio/compare/3.1.0...3.1.1

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4633275085357056/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4633275085357056/?repo_name=Workiva%2Fw_dio&pull_number=5)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by robbecker-wf — APPROVED** [review]

**Comment by semveraudit-wf** [comment]
### Public API Changes

<p><em><strong>Release PR detected; using previous release (3.1.0) as the diff base.</strong></em></p> No changes to the public API found for commit 97c89ae1884bd34620e5fdc6b9cb07f6ab611a0f

Showing results for 97c89ae1884bd34620e5fdc6b9cb07f6ab611a0f
> Powered by [semver-audit-service](https://github.com/Workiva/semver-audit-service). Please report any problems by [filing an issue](https://github.com/Workiva/semver-audit-service/issues).
> Reported by the dart semver audit client 2.2.2
[Browse public API](https://semver-audit.wk-dev.wdesk.org/Workiva/w_dio/97c89ae1884bd34620e5fdc6b9cb07f6ab611a0f).

**Comment by robbecker-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
